### ISSUE TITLE
Preprocessing Method for the Dataset

### ISSUE THREAD

**Issue by amansinha09** [kepsail/ie-HGCN#1]
Hi,

Can you provide the preprocessing methods you applied on the dataset, or the preprocessed dataset itself? 
It would be very helpful.

Many thanks!

**Comment by kepsail** [comment]
Thanks for your interest. The preprocessed dataset are too large to be posted on GitHub. Please E-mail me (ymyang@stu.xidian.edu.cn), and I will send them to you.
